name: Python Package using Conda

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Conda on Linux/macOS
      if: runner.os != 'Windows'
      run: |
        if [ $RUNNER_OS = "Linux" ]; then
          wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo $HOME/miniconda/bin >> $GITHUB_PATH
          $HOME/miniconda/bin/conda init bash
          source $HOME/.bashrc
        elif [ $RUNNER_OS = "macOS" ]; then
          wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo $HOME/miniconda/bin >> $GITHUB_PATH
          $HOME/miniconda/bin/conda init bash
          source $HOME/.bash_profile
        fi
    - name: Set up Conda on Windows
      if: runner.os == 'Windows'
      run: |
        choco install miniconda3
        $env:Path += ";C:\tools\miniconda3\Scripts;C:\tools\miniconda3"
        conda init powershell
        conda config --set auto_activate_base false
    - name: Create and activate environment
      run: |
        conda create --name test-env python=${{ matrix.python-version }} -y
        source activate test-env || conda activate test-env
    - name: Install app with pip
      run: |
        pip install -e .
    - name: Lint with flake8
      run: |
        conda install flake8 -y
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest -y
        pytest
